```{r}
remotes::install_github("eco4cast/neon4cast", force=TRUE)
library(dplyr)
URL = "https://data.ecoforecast.org/neon4cast-targets/phenology/phenology-targets.csv.gz"
```
```{r}
data = readr::read_csv(URL, col_names = c("Date", "Siteid", "Variable", "Observation"))
harv = na.omit(data[data$Siteid == "HARV",]) # filter by Harvard Forest site
time = as.Date(harv$Date)
```
```{r}
gcc_90 = harv[harv$Variable == "gcc_90",]
rcc_90 = harv[harv$Variable == "rcc_90",]
```

```{r}
weather_stage3 <- neon4cast::noaa_stage3()
ds1 <- weather_stage3 |> 
  dplyr::filter(site_id == "HARV") |>
  dplyr::collect()
```
```{r}
TMP = ds1[ds1$variable == "air_temperature",]
PRES = ds1[ds1$variable == "air_pressure",]
RH  = ds1[ds1$variable == "relative_humidity",]
PCP  = ds1[ds1$variable == "preciptation_flux",]
```

```{r}
RandomWalk = "
model{
  
  #### Data Model
  for(t in 1:n){
    y[t] ~ dnorm(x[t],tau_obs)
  }
  
  #### Process Model
  for(t in 2:n){
    x[t]~dnorm(x[t-1],tau_add)
  }
  
  #### Priors
  x[1] ~ dnorm(x_ic,tau_ic)
  tau_obs ~ dgamma(a_obs,r_obs)
  tau_add ~ dgamma(a_add,r_add)
}
"
```

```{r}
y <- as.numeric(gcc_90$Observation)

data1 <- list(y=log(y),n=length(y),      ## data
             x_ic=log(0.4),tau_ic=100, ## initial condition prior
             a_obs=1,r_obs=1,           ## obs error prior
             a_add=1,r_add=1            ## process error prior
             )
```

```{r}
nchain = 3
init <- list()
for(i in 1:nchain){
  y.samp = sample(y,length(y),replace=TRUE)
  init[[i]] <- list(tau_add=0.1/var(diff(log(y.samp))),  ## initial guess on process precision
                    tau_obs=0.5/var(log(y.samp)))        ## initial guess on obs precision
}
```

```{r}
library(rjags)
j.model   <- jags.model (file = textConnection(RandomWalk),
                             data = data1,
                             inits = init,
                             n.chains = 3)
```
```{r, fig.asp = 1.0}
## burn-in
jags.out   <- coda.samples (model = j.model,
                            variable.names = c("tau_add","tau_obs"),
                                n.iter = 1000)
plot(jags.out)
```
```{r}
jags.out   <- coda.samples (model = j.model,
                            variable.names = c("x","tau_add","tau_obs"),
                            n.iter = 1000,
                            init = init)
jags.out <- window(jags.out, start=100)
```

```{r}
time.rng = c(1,length(time))       ## adjust to zoom in and out
out <- as.matrix(jags.out)         ## convert from coda to matrix  
x.cols <- grep("^x",colnames(out)) ## grab all columns that start with the letter x
ci <- apply(exp(out[,x.cols]),2,quantile,c(0.025,0.5,0.975)) ## model was fit on log scale
plot(time[0:2565],ci[2,],type='n',ylim=range(y,na.rm=TRUE),ylab="GCC",xlab = "Date",log='y',xlim=time[time.rng])
## adjust x-axis label to be monthly if zoomed
if(diff(time.rng) < 100){ 
  axis.Date(1, at=seq(time[time.rng[1]],time[time.rng[2]],by='month'), format = "%Y-%m")
}
ecoforecastR::ciEnvelope(time,ci[1,],ci[3,],col=ecoforecastR::col.alpha("lightBlue",0.75))
points(time[0:2565],y,pch="+",cex=0.5)
```

